---
- hosts: devopsslave1
  become: true
  tasks:
    -  name: install java
       yum:
        name: java-1.8.0-openjdk.x86_64
        state: present

    - name: Set JAVA_HOME
      lineinfile:
        dest: /etc/environment
        state: present
        regexp: '^JAVA_HOME'
        line: 'JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk'    
